shorebirdtech/handbook

ceo.md
=> Typo and consistency in headings

company.md
Unless 'pain of glass' is a pun on the issues at hand to solve. 😜
=> Fix typo in company.md

company.md
=> chore: Add url to discord

company.md
Adding a short blurb about myself
=> docs(company): add Felix to Team

benefits.md
=> First pass at benefits.md

benefits.md
I wrote this up a while ago, just finally committing.
=> docs: add a note about compensation philosophy

security.md
This came up as part of a customer review.
=> docs: add a security policy

astro.config.mjs, package-lock.json
I got a warning via email, so ran it.  Also added /benefits to the side bar.
=> npm upgrade

src/content/docs/company.md
These were things we learned from doing the rollout feature.  Taken in part from a Google doc and embelished a little.
=> docs: document product values

src/content/docs/Compliance/compliance-policy.md, src/content/docs/Compliance/vendor-policy.md
Per ISO certification. This template is mostly from OneLeet and customized for our needs.
=> feat: adding vendor policy

src/content/docs/Compliance/remote-work-policy.md
Kind of interesting given that we are all remote workers 😂 
Per ISO requirements but has been modified to fit what we currently do.
=> feat: add remote work policy

src/content/docs/Compliance/change-management-policy.md
=> feat: add change management policy

cspell.config.yaml, src/content/docs/Compliance/code-of-conduct.md
=> feat: add code of conduct

cspell.config.yaml, src/content/docs/Compliance/secure-development.md
Per ISO requirements. This is all stuff we are already doing, just writing it down.
=> feat: add secure development policy

cspell.config.yaml, src/content/docs/Compliance/business-continuity-and-disaster-recovery.md
=> feat: add continuity and disaster recovery policy

src/content/docs/Compliance/physical-security-policy.md
=> feat: add physical security policy

src/content/docs/Compliance/information-security-policy.md
=> feat: add information security policy

src/content/docs/Compliance/vulnerability-management-policy.md
=> feat: add vulnerability policy

cspell.config.yaml, src/content/docs/Compliance/data-management-retention-policy.md
=> feat: add data management & retention policy

src/content/docs/Compliance/access-management-policy.md
=> feat: add access management policy

src/content/docs/Compliance/encryption-key-management-policy.md
=> feat: add key management policy

src/content/docs/Compliance/incident-response-policy.md
=> feat: add incident response policy

src/content/docs/Compliance/logging-monitoring-policy.md, src/content/docs/Compliance/physical-security-policy.md, src/content/docs/Compliance/risk-manangement-policy.md, src/content/docs/Compliance/vendor-policy.md
=> feat: add logging & monitoring policy

cspell.config.yaml, src/content/docs/Company/onboarding.md
Being done for ISO requirements but also updating this with my personal experience of onboarding this year. The biggest thing (requirements wise) is the "Start Week" section as we lay out the requirements that a new employee has to have a successful first week with us.
=> feat: update onboarding

cspell.config.yaml, src/content/docs/Company/offboarding.md
Taking a first pass at this for ISO requirements as we didn't have one documented.
=> feat: add offboarding documentation

src/content/docs/Company/onboarding.md
More we could move, but this is a big chunk.
=> chore: move more content from our private onboarding doc to our public one
